- name: DBRM Bakup Job template render
  template:
    src: './files/DBRMBKUP.j2'
    dest: '/tmp/DBRMBKUP.bin'
  register: result

- name: DBRM Backup Job Template Response
  debug:
    msg: "{{ result }}"
       
- name: Convert DBRM backup Job JCL file encoding from ISO8859-1 to IBM-1047
  zos_encode:
    src: '/tmp/DBRMBKUP.bin'
    dest: '/tmp/DBRMBKUP.jcl'
    to_encoding: IBM-1047
    from_encoding: ISO8859-1
  register: result

- name: DBRM Copy backup JCL Encoding conversion response
  debug:
    msg: "{{ result }}"   

- name: Submit the job from USS
  zos_job_submit:
    src: '/tmp/DBRMBKUP.jcl'
    location: USS
    wait: true
  register: result

- name: Job Response
  debug:
    msg: "{{ result.jobs[0].ret_code }}"