- name: DBRM Copy Job template render
  template:
    src: './files/DBRMCOPY.j2'
    dest: '/tmp/DBRMCOPY.bin'
  register: result

- name: DBRM Copy Job Template Response
  debug:
    msg: "{{ result }}"
       
- name: Convert DBRM Copy Job JCL file encoding from ISO8859-1 to IBM-1047
  zos_encode:
    src: '/tmp/DBRMCOPY.bin'
    dest: '/tmp/DBRMCOPY.jcl'
    to_encoding: IBM-1047
    from_encoding: ISO8859-1
  register: result

- name: DBRM Copy Job JCL Encoding conversion response
  debug:
    msg: "{{ result }}"   

- name: Submit the job from USS
  zos_job_submit:
    src: '/tmp/DBRMCOPY.jcl'
    location: USS
    wait: true
  register: result

- name: Job Response
  debug:
    msg: "{{ result.jobs[0].ret_code }}"