- name: Job template render for LOAD module rollback
  template:
    src: './files/LOADROLB.j2'
    dest: '/tmp/LOADROLB.bin'
  register: result

- name: LOAD module rollback - Template Response
  debug:
    msg: "{{ result }}"
       
- name: Convert LOAD rollback JCL encoding from ISO8859-1 to IBM-1047
  zos_encode:
    src: '/tmp/LOADROLB.bin'
    dest: '/tmp/LOADROLB.jcl'
    to_encoding: IBM-1047
    from_encoding: ISO8859-1
  register: result

- name: LOAD rollback JCL Encoding conversion response
  debug:
    msg: "{{ result }}"   

- name: Submit the job from USS
  zos_job_submit:
    src: '/tmp/LOADROLB.jcl'
    location: USS
    wait: true
  register: result

- name: Job Response
  debug:
    msg: "{{ result.jobs[0].ret_code }}"