---
- name: Rollback Z {{ type }} Application
  hosts: all

  gather_facts: no
 
  collections:
    - ibm.ibm_zos_core
  
  vars_files: "./group_vars/deploy_vars.yml"

  environment: "{{ environment_vars }}"  
  
  tasks:  
    - name: Rollback Load modules in target PDS
      include_tasks: "./tasks/rollback_load.yml"

    - name: Rollback DBRMs in target PDS
      include_tasks: "./tasks/rollback_dbrm.yml"
      when: (db2 == true)

    - name: Bind DBRMs to DB2 Plan
      include_tasks: "./tasks/db2_bind.yml"    
      when: (db2 == true)

    - name: CICS Refresh
      include_tasks: "./tasks/cics_refresh.yml"    
      when: (cics == true)    
...    
